environment:
  coordinate_system: cartesian
  grid_shape: [220, 200, 1]
  cell_size: [1.e-2, 1.e-2, 1.e-2]
  external_magnetic_field: [0, 0, 2.e-2]  # array or file.csv
  external_electric_field: [2.e+4, 0, 0]
  field_dtype: fp64

grids:
  -
    species: electron
    backend: gpu
    n_splits: [2, 1, 1]
    n_computational_to_physical: 1
    dtype:
      X: fp32
      U: fp32
    initial_condition:
      sample: random
      n_particles: 2.5e+8
      avg_velocity: 3.e+6
      tracking:
        n_particles: 10
        sample: random

  -
    species: ion
    backend: gpu
    n_splits: [2, 1, 1]
    n_computational_to_physical: 1
    dtype:
      X: fp32
      U: fp32
    initial_condition:
      sample: random
      n_particles: 2.5e+8
      avg_velocity: 1.e+6
      tracking:
        n_particles: 10
        sample: random

simulation:
  delta_time: 1.e-11
  n_cycles: 40

  backend: mpi
  particles_spare_memory: 0.5

  filepath: ./test.h5
  checkpoint_strategy:
    save_particles_frequency: 40
    save_field_frequency: 1
    save_tracked_frequency: 1
